### ISSUE TITLE
Doesn't detect mounting LUKS encrypted volumes

### ISSUE THREAD

**Issue by xhujerr** [fernandotcl/udisks-glue#10]
I ran udisks-glue -f . I can see mounting regular volume:
Device file /dev/sdb1 mounted at /media/user/Kingston

... but I have LUKS encrypted volume which has device in /dev/dm-\* (with symlink in /dev/mapper/).  I suppose /dev/mapper/ is not monitored, is it?

**Comment by fernandotcl** [comment]
udisks-glue can see everything udisks sends to DBus. You can use "udisks --monitor" to see what udisks events are sent. If you find udisks-glue's filters don't allow you to match the udisks events that you need, feel free to open a ticket with more information.

Also note that udisks has been superseded by udisks2, which is incompatible with udisks-glue. I'd recommend looking for alternatives unless you're stuck with udisks for some reason.
