### ISSUE TITLE
udisks-glue gives error 255

### ISSUE THREAD

**Issue by Sjoerd82** [fernandotcl/udisks-glue#11]
udisks-glue gives error 255

I don't recognize code 255, it's not registered with the mount command, at least not in the man page. Does it come from udisks-glue? If so, what does it mean?

`# mount /dev/sda1 /media/SJOERD`
Works fine (SJOERD is the flash drive label), however, automounting it does not:

```
# /usr/bin/udisks-glue -c /etc/udisks-glue.conf --foreground
Device file /dev/sda inserted
Device file /dev/mmcblk0 inserted
Device file /dev/mmcblk0p1 inserted
Trying to automount /dev/mmcblk0p1...
Failed to automount /dev/mmcblk0p1: Error mounting: mount exited with exit code 255: mount: mounting /dev/mmcblk0p1 on /media/CFAB-84EE failed: Invalid argument

Device file /dev/sda1 inserted
Trying to automount /dev/sda1...
Mount failed: Error mounting: mount exited with exit code 255: mount: mounting /dev/mmcblk0p1 on /media/CFAB-84EE failed: Invalid argument

Failed to automount /dev/sda1: Error mounting: mount exited with exit code 255: mount: mounting /dev/sda1 on /media/SJOERD failed: Invalid argument

Mount failed: Error mounting: mount exited with exit code 255: mount: mounting /dev/sda1 on /media/SJOERD failed: Invalid argument
```

-----------------------------------
The config file:

filter disks {
    optical = false
    partition_table = false
    usage = filesystem
}

match disks {
    automount = true
    automount_options = { "ro", "noexec", "nosuid", "nodev", "noatime", "sync", "dmask=0000" }
    post_insertion_command = "udisks --mount %device_file"
}

**Comment by fernandotcl** [comment]
You have both automount and a post insertion command that attempts to mount the device, you probably want one or the other. I realize that the man page has an example with both, I haven't touched udisks-glue in years but I don't think that's correct.

The error message doesn't come from udisks-glue, but rather from udisks through D-Bus. The mention to exit code 255 is in the error message we get from udisks.

As for why this all isn't working for you, It doesn't sound like udisks-glue is involved. Try playing with udisks' D-Bus interface to troubleshoot.

**Comment by Sjoerd82** [comment]
Thanks. I'm on buildroot with only a limited number of installed packages. After installing every mount-related package it worked. I'm not (yet) sure which package exactly it was that was missing, but it's solved now. :)
