### ISSUE TITLE
glib2.0 not available on Ubuntu 20.04 -- how to circumvent?

### ISSUE THREAD

**Issue by RuiApostolo** [fernandotcl/udisks-glue#12]
Hi,

glib2.0 has been deleted from Ubuntu's 20.04 PPA stream -- https://www.ubuntuupdates.org/package/ubuntu-desktop_ppa/focal/main/base/glib2.0
Is there any way to still use udisks-glue?

**Comment by fernandotcl** [comment]
udisks-glue hasn't been updated to use more recent dependencies, so it's up to you to make it work, install older dependencies yourself, etc, if you still want to use udisks-glue unmodified.
