### ISSUE TITLE
udisks-glue does not compile anymore

### ISSUE THREAD

**Issue by chmduquesne** [fernandotcl/udisks-glue#6]
Hi,

On archlinux, udisks-glue does not compile anymore.

The compilation fails on:
main.c: In function ‘main’:
main.c:171:5: error: ‘g_type_init’ is deprecated (declared at /usr/include/glib-2.0/gobject/gtype.h:669) [-Werror=deprecated-declarations]
     g_type_init();
     ^

This could probably easily fixed by removing -Werror from the default flags. Or, cleaner, the call to g_type_init() could be simply removed, since gtype.h says:
- Deprecated: 2.36: g_type_init() is now done automatically

Regards,
Christophe-Marie

**Comment by fernandotcl** [comment]
Hmmm I see. Since 2.36 was just recently released, would you mind wrapping g_type_init() in a compile-time version check and submitting a new pull request? Thanks!

**Comment by chmduquesne** [comment]
Yup! Done...

**Comment by fernandotcl** [comment]
I have merged a slightly modified version of your patch, thank you. Note that GLIB_VERSION_2_36 isn't defined before 2.36, so it evaluates to 0. :-)
