### ISSUE TITLE
The name org.freedesktop.UDisks was not provided by any .service files

### ISSUE THREAD

**Issue by kierun** [fernandotcl/udisks-glue#9]
Ran into a problem... Running udisk-glue within Fedora 20 with Awesome, I get this error: 

```
; udisks-glue --config ~/.udisks-glue.conf --foreground 
Unable to enumerate the devices: The name org.freedesktop.UDisks was not provided by any .service files
```

What am I missing?

**Comment by fernandotcl** [comment]
udisks itself, I assume. Newer versions of distributions should no longer be shipping udisks by default.

Anyways, please contact your distro's support channels if you need help with this.
